# Generated by Django 5.0.2 on 2024-03-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
    ]
