# Generated by Django 5.0.2 on 2024-03-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_group_of_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_of_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.students_group'),
        ),
    ]
